### ISSUE TITLE
Indexing and natural iteration order

### ISSUE THREAD

**Issue by dgrnbrg** [stainless-steel/matrix#3]
I would like to add a trait for indexable matrices, so that the `get` API of the compressed sparse representation, the packed representation, etc. can be used generically. Here's the trait I'm planning to use:

```rust
pub trait Indexed<T>: Size {
    /// This retrieves the element at the specified position in the matrix, or None if it's out of
    /// bounds
    fn get(&self, position: (usize,usize)) -> Option<&T>;
}
```

Additionally, I'd like to make an iteration API to go along with this trait. I want an API that returns the nonzero indices of the array in the most efficient order for iteration (i.e. so that each index pair is contiguous in memory to maximize cache efficiency). Currently, I have a few ideas as to what this API could look like:

1. We could have a trait that returns an iterator of `(usize,usize)` pairs, in the most efficient traversal order.
2. We could have a trait that returns an iterator of `(usize,usize,&T)` triples, to avoid the extra call to `get` during iteration.
3. We could have an iterator-like API that supports "feedback" to the iterator, so that every element would be passed to a callback, and the callback could control the iteration by requesting `Next`, `NextRow`, `NextCol`, etc. This would require disambiguating row-major & column-major traversals at the API level, since `NextRow`/`NextCol` only make sense for row/column-major layouts, respectively.

What are your thoughts on generic matrix iteration? Do you have strong preferences as to the API?

p.s. For my problem, I use primarily Conventional, Packed, and CSC matrices, in case I have unconscious API biases.

**Comment by IvanUkhov** [comment]
Thanks for the issue!

A trait for indexable matrices sounds good, and an API for iterating over specific elements of a matrix sounds good as well. I only want to make sure that we make use of the standard library as much as possible in order to maximize interoperability. Regarding indexing, `Index` and `IndexMut` from `std::ops` are worth looking at. Similarly, the iterating API should play well with `Iterator` and `IntoIterator` from `std::iter`. Regarding your three options, I like the second the most.

**Comment by IvanUkhov** [comment]
> To me, then, there's a greater abstraction issue: in order to build an indexable API, we need to be able to return values that are not in the range covered by the packed representation. Thus, the packed matrix couldn't have an index API.

Yes, right. But then pretty much all of the representations won’t be able to have this API according to your definition. Only `Conventional` can have it, and it’s also possible for symmetric packed matrices.

What if we define indexing as iterating only over those elements that are explicitly stored by the representation in question? In fact, it has already been done for `Banded` and `Compressed`; have a look at [`banded::Iterator`](https://docs.rs/matrix/0.21.8/matrix/format/banded/struct.Iterator.html), [`compressed::Iterator`](https://docs.rs/matrix/0.21.8/matrix/format/compressed/struct.Iterator.html), and [`compressed::IteratorMut`](https://docs.rs/matrix/0.21.8/matrix/format/compressed/struct.IteratorMut.html). I think we could proceed in the same vein for the other formats. What do you think about this definition?
