### ISSUE TITLE
Provide a neighbours method

### ISSUE THREAD

**Issue by hellow554** [stainless-steel/matrix#6]
It is often required to iterate over all the neighbours, which are either 8 or less, depending on the position in the grid (elements on the dege have fewer neighbours, down to 3 in a corner).

The typical solution won't work here, where you iterate over `-1, 0, 1` and just add that to the position, because `usize` cannot be `-1`, which increases the error rate on implementing such.

I would suggest to provide a new struct `Neighbours` (or `Neighbor` if you want that ;) ) and implement `IntoIterator` for that. Then provide methods to gain the struct from a Matrix (maybe implementing it on the `Matrix` trait itself? Not sure, if that works though :/) and let the user iterate.

**Comment by IvanUkhov** [comment]
Thanks for the note. It sounds a bit esoteric. Not sure if this functionality is of general interest.
