### ISSUE TITLE
Overlap between matrix's Element trait and num-trait's Zero trait

### ISSUE THREAD

**Issue by BlinkyStitt** [stainless-steel/matrix#7]
I'm trying to use matrix and bigdecimal together. I figured it would be simple because they both use the num-* crates. However, I ran into this issue: https://github.com/akubera/bigdecimal-rs/issues/48

While looking into how to implement Element, I noticed that the trait is pretty much identical to num-trait's Zero trait. Is there any reason for this duplication?

BigDecimal already impls Zero (https://github.com/akubera/bigdecimal-rs/blob/master/src/lib.rs#L697), so I think changing matrix to just expect the Zero trait would make crates work without needing to impl matrix::Element, too.

**Comment by BlinkyStitt** [comment]
Hmm. BigDecimal doesn't (and can't) implement Copy. Any suggestions for working around that requirement?

**Comment by IvanUkhov** [comment]
Thanks for the issue and sorry for the late reply! `Copy` is currently required by `Element`. I don’t remember why it had to be like that. If you have time, you could try to lift this requirement; I’ll be happy to review your changes and, if everything continues to work as it does right now, accept them.
