### ISSUE TITLE
Provide default impl for Element::is_zero

### ISSUE THREAD

**Issue by hellow554** [stainless-steel/matrix#9]
should be pretty trivial

```rust
fn is_zero(&self) -> bool {
    self == &Self::zero()
}
```

**Comment by IvanUkhov** [comment]
Thanks for the issue! I’m wondering why they [didn’t take](https://docs.rs/num-traits/0.2.5/src/num_traits/identities.rs.html#5-26) this approach in `num`. Perhaps there are some caveats that we don’t see at the moment. Any ideas?

**Comment by IvanUkhov** [comment]
Other than that, I have no problem with this change. Please feel free to open a pull request.

**Comment by hellow554** [comment]
I think it's because in num the trait doesn't require the type to be `Copy`able, but [matrix does](https://github.com/stainless-steel/matrix/blob/master/src/element.rs#L4)
